# -*- coding: utf-8 -*-
"""Greeting Service.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cPYtKEy5cPpLa7N0tR8g0US12U9CVDew

# GREETING DASHBOARD
"""

import os

class Greetings:
    def __init__(self):
        self.greetings_storage = {}
        self.load_config()

    def load_config(self):
        self.greetings_storage = {
            lang: greet for lang, greet in os.environ.items() if lang.startswith("GREET_")
        }
        print("GREETING DASHBOARD!")
        print("Greetings Storage: ", self.greetings_storage)

    def user_info(self, lang, user):
        self.language = lang
        self.user_name = user
        self.greet()

    def greet(self):
        if self.language in self.greetings_storage:
            print(self.greetings_storage[self.language], self.user_name)
        else:
            print("Sorry, greeting not available in", self.language)

    def store(self, greets):
        self.greetings_storage = greets
        print(self.greetings_storage)

greetObj = Greetings()

"""# ADMIN DASHBOARD"""

# ADMIN

# print("Enter the Languge")
# languge = input()

# print("Enter the Greeting")
# greet = input()

# greetObj.store(languge , greet)

greetingsStorage = {
    "URDU": "Assalam o' Alaikum",
    "ENGLISH" : "Welcome",
    "JAPANESE" : "Konichiwa"
}

greetObj.store(greetingsStorage)

"""# USER DASHBOARD"""

# USER
print("Enter your languge")
languge = input()

print("Enter your User Name")
user = input()

greetObj.user_info(languge , user)

"""# **TESTING**"""

import unittest

class TestGreetings(unittest.TestCase):
    def setUp(self):
        self.greetObj = Greetings()
        
    def test_user_info(self):
        self.greetObj.user_info('English', 'John')
        self.assertEqual(self.greetObj.language, 'English')
        self.assertEqual(self.greetObj.user_name, 'John')
        
    def test_greet(self):
        self.greetObj.store({'English': 'Hello', 'Spanish': 'Hola'})
        self.greetObj.user_info('English', 'John')
        self.assertEqual(self.greetObj.greetings_storage['English'], 'Hello')
        
    def test_store(self):
        self.greetObj.store({'English': 'Hello', 'Spanish': 'Hola'})
        self.assertEqual(self.greetObj.greetings_storage, {'English': 'Hello', 'Spanish': 'Hola'})

# if __name__ == '__main__':
#   unittest.main()

if __name__ == '__main__':
    unittest.main(argv=['first-arg-is-ignored'], exit=False)

"""# **README**

This code defines a Greetings class that has the following functionality:



1.   Initializes an empty dictionary greetings_storage and calls the load_config method when an instance of the class is created.
2.   load_config method loads the environment variables that start with "GREET_" and adds them to the greetings_storage dictionary, then it prints "GREETING DASHBOARD!" and the current greetings_storage
3. user_info method takes in a lang and user arguments and assigns them to language and user_name attributes of the instance, then calls the greet method.
4. greet method checks if the language attribute of the instance is a key in the greetings_storage dictionary, if it is, it prints the value at that key along with the user_name attribute, otherwise it prints "Sorry, greeting not available in" followed by the language attribute.
5. store method takes in a dictionary greets and assigns it to the greetings_storage attribute, then prints the new greetings_storage.
6. An instance of the Greetings class is created at the end of the code and assigned to the variable greetObj.

# This implementation follows the **Twelve-Factor App** principles by:



1.   Storing the greetings in the environment variables(config) under GREET_ prefix
2.   Loading the config in the constructor to initialize the greetings storage
3.   Treating the greetings storage as an attached resource
4.   Keeping the greet method stateless by only using the language and user_name properties
5. Not using any backing service
6. Not providing any admin process

You can run this code by setting the environment variables with the format GREET_LANGUAGE="GREETING_MESSAGE" and running the script with python.
"""











